### ISSUE TITLE
Issues with Unity 2021.2.17f1

### ISSUE THREAD

**Issue by ManuelRauber** [Cyanilux/ShaderGraphToPNG#1]
Hi there!

I was trying to make a nice PNG for the following Shader Graph:

![image](https://user-images.githubusercontent.com/740791/161765530-f2f4707a-5862-4a41-ac14-afc8548de21c.png)

The result of your tool is:

![WindEffect Shader](https://user-images.githubusercontent.com/740791/161765617-3013b476-13fe-4a94-9c46-780985c421a0.png)

* Unity 2021.2.17f1 (Apple Silicon Version)
* URP 12.1.6 (I guess that's also the Shader Graph version then)
* ShaderGraphToPNG 1.0.1 (installed via git in Package Manager)

Please let me know if you need any other information to find the issue. :)

Thanks!

**Comment by Cyanilux** [comment]
Hey! Hmm, It works fine on Windows, so I'd guess the Apple Silicon is the cause. I'd assume there are values in the [DoShaderGraphToPng](https://github.com/Cyanilux/ShaderGraphToPNG/blob/2ec7eafd6650660b0201c862aa90e4295f3b47c6/Editor/GraphToPng.cs#L260) function that is incorrect for that OS. I'm not really that surprised, as we did a lot of trial and error to get it to work even on Windows.
Since this isn't an OS I have available I won't be able to debug this, but if you (or anyone else that comes across this issue) feels comfortable with editor scripting that's probably the place to look into first.

**Comment by ManuelRauber** [comment]
I just noticed, that it works, if I do not maximize the Shader Graph window. Without maximizing it produces a nice screenshot of the whole graph. 
So I guess that's the workaround for macOS :)

**Comment by Flabidouf** [comment]
Tried on Apple Silicon with Unity 6 and it doesn't work. It captures parts of the window and adds them together, creating a strange mashup.
I tried to not maximize the Shader Graph window but to good.

<img width="7789" height="4435" alt="Image" src="https://github.com/user-attachments/assets/77449fc1-c41d-475b-bac4-c52ee5418e26" />
